version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

  ghost:
    image: ghost
    volumes:
      - ./ghost_data:/var/lib/ghost/content
    environment:
      - url=http://3.36.115.79:8000